version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Ignore updates to @types/node as we want support for NodeJS LTS
      - dependency-name: "@types/node"
      - dependency-name: "strip-json-comments"
    # Disable version updates for npm dependencies - keep only security updates
    open-pull-requests-limit: 0